# https://github.com/krishnassh/dotfiles
# Author: KrishnaSSH
# LICENSE: CC0 1.0 Universal
# You may get a copy of this license from https://creativecommons.org/publicdomain/zero/1.0/legalcode.en

# Guide
# Alt + O instead of Ctrl + B as it's more intuitive
# Alt + O + [ and then work with vim bindings
# Alt + O + U to create a vertical pane
# Alt + O + I to create a horizontal pane
# Shift + H, J, K, L to resize panes
# Alt + O + H, J, K, L to select different panes 


unbind C-b
unbind '"'
unbind '%'

set-option -g prefix M-o
bind-key M-o send prefix

set -g mouse on
set -g base-index 1
set -g pane-base-index 1

set -g status-position bottom 
set -g status-justify left
set -g status-style 'fg=green, bg=black'

bind u split-window -h
bind i split-window -v


bind h select-pane -L 
bind l select-pane -R 
bind k select-pane -U 
bind j select-pane -D 


bind -r H resize-pane -L 10
bind -r L resize-pane -R 10
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5

bind r source-file ~/.tmux.conf



set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi V send -X select-line

set -s copy-command 'wl-copy'

bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
