; https://github.com/krishnassh/dotfiles
; Author: KrishnaSSH
; LICENSE: CC0 1.0 Universal
; You may get a copy of this license from https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

(setq custom-file "~/.config/emacs/emacs.autogenerated.el")
(setq inhibit-startup-message t)

(scroll-bar-mode -1)    ; disable visible scrollbar
(tool-bar-mode -1)      ; disable the toolbar
(tooltip-mode -1)       ; disable tooltips
(set-fringe-mode 10)    ; more room
(menu-bar-mode -1)           ; disable menu bar

;; tilda files in ~/.local/state/emacs/backups/
(defvar backup-dir "~/.local/state/emacs/backups/")
;; create the directory if it doesn't exist.
(make-directory backup-dir t)
(setq backup-directory-alist
      `(("." . ,backup-dir)))

;; relative line numbers
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)

;; font faces
(set-face-attribute 'default nil :font "Iosevka" :height 200)

;; initializing package sources
(require 'package)
(setq package-archives '(("melpa"  . "https://melpa.org/packages/")
			 ("org"  . "https://orgmode.org/elpa/")
			 ("elpa"  . "https://elpa.gnu.org/")))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)

;; evil mode
(setq evil-want-integration t)
(setq evil-want-keybinding nil) 

(use-package evil
  :ensure t
  :init
  :config
  (evil-mode 1))

(use-package evil-collection
  :ensure t
  :after evil
  :config
  (evil-collection-init))

;; theme
(use-package gruber-darker-theme
  :init
  (load-theme 'gruber-darker t))

;; discord rpc
(use-package elcord
  :config
  (elcord-mode))

(load-file custom-file)
