; https://github.com/krishnassh/dotfiles
; Author: KrishnaSSH
; LICENSE: CC0 1.0 Universal
; You may get a copy of this license from https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt

(setq custom-file "~/.config/emacs/emacs.autogenerated.el")
(setq inhibit-startup-message t)

(scroll-bar-mode -1)    ; disable visible scrollbar
(tool-bar-mode -1)      ; disable the toolbar
(tooltip-mode -1)       ; disable tooltips
(set-fringe-mode 10)    ; more room
(menu-bar-mode -1)      ; disable menu bar

;; tilda files in ~/.local/state/emacs/backups/
(defvar backup-dir "~/.local/state/emacs/backups/")
;; create the directory if it doesn't exist.
(make-directory backup-dir t)
(setq backup-directory-alist
      `(("." . ,backup-dir)))

;; relative line numbers
(setq display-line-numbers-type 'relative)
(global-display-line-numbers-mode 1)

;; font faces
(set-face-attribute 'default nil :font "JetBrainsMono Nerd Font" :height 170)

;; initializing package sources
(require 'package)
(setq package-archives '(("melpa"  . "https://melpa.org/packages/")
			 ("org"  . "https://orgmode.org/elpa/")
			 ("elpa"  . "https://elpa.gnu.org/")))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(unless (package-installed-p 'use-package)
  (package-install 'use-package))
(require 'use-package)
(setq use-package-always-ensure t)


;; standard emacs bindings
;; todo

;; evil mode
(setq evil-want-integration t)
(setq evil-want-keybinding nil) 

(use-package evil
  :ensure t
  :init
  :config
  (evil-mode 1)
  ;; evil keymaps
  (evil-set-leader 'normal (kbd "SPC"))
  (evil-define-key 'normal 'global (kbd "<leader>e") 'find-file)
  (evil-define-key 'normal 'global (kbd "<leader>o") 'other-window)
  (evil-define-key 'normal 'global (kbd "<leader>x") 'delete-window)
  (evil-define-key 'normal 'global (kbd "<leader>t") 'my/vterm-down)
  (evil-define-key 'normal 'global (kbd "<leader>k") 'kill-buffer)
  (evil-define-key 'normal 'global (kbd "<leader>b") 'switch-to-buffer)
  (evil-define-key 'normal 'global (kbd "<leader>n") 'next-buffer)
  (evil-define-key 'normal 'global (kbd "<leader>p") 'previous-buffer)
  (evil-define-key 'normal 'global (kbd "<leader>r") 'eval-buffer)

  ;; swap ; and : in normal mode
  (evil-define-key 'normal 'global (kbd ";") 'evil-ex)
  (evil-define-key 'normal 'global (kbd ":") 'evil-repeat-find-char)

  )

(use-package evil-collection
  :ensure t
  :after evil
  :config
  (evil-collection-init)
;  (evil-set-initial-state 'vterm-mode 'emacs))
  )

;; theme
(use-package gruber-darker-theme
  :ensure t
  :config
  (load-theme 'gruber-darker t))

;; discord rpc
(use-package elcord
  :hook (after-init . elcord-mode))

;; vterm
(use-package vterm)
(add-hook 'vterm-mode-hook
          (lambda ()
            (set-process-query-on-exit-flag (get-buffer-process (current-buffer)) nil)))

;; my functions

(defun my/vterm-down ()
  "Open vterm window below the current buffer"
  (interactive)
  (split-window-below)
  (other-window 1)
  (vterm))

(defun my/vterm-right ()
  "Open vterm window side to the current buffer"
  (interactive)
  (split-window-right)
  (other-window 1)
  (vterm))

(load custom-file 'noerror)
