# https://github.com/krishnassh/dotfiles
# Author: KrishnaSSH
# LICENSE: CC0 1.0 Universal
# You may get a copy of this license from https://creativecommons.org/publicdomain/zero/1.0/legalcode.en

[main]
font=Dejavu Sans Mono:size=10.5
include=/usr/share/foot/themes/kitty
[colors-dark]
background=000000
alpha=0.8

[bell]
urgent=no
notify=no
visual=no

[csd]
preferred=server

